language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn --batch-mode --errors --fail-at-end --show-version -s build/settings.xml -Dpartners.v8.1c.ru.username=$USERNAME_1C -Dpartners.v8.1c.ru.password=$PASSWORD_1C clean verify -f build/pom.xml
